
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  backend:
  frontend:
