
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    volumes:
      - ./app/backend:/app
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:6969

volumes:
  backend:
  frontend:

networks:
  app-network:
    driver: bridge
